blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Cloudflared Tunnel
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: homebridge-cloudflared-tunnel - Pull Requests
    url: https://github.com/donavanbecker/homebridge-cloudflared-tunnel/pulls
    about: Please report security vulnerabilities here.
