name: AutoDependabot

on:
  pull_request:
  push:
    branches:
    - beta

jobs:
  automerge:
    name: Auto-merge dependabot updates
    runs-on: ubuntu-latest
    steps:
      - uses: mitto98/dependabot-automerge-action@v1.0.2
        with:
          token: ${{ github.token }}
          merge: true
